/* Generated by Report Generator v3.14 (R2013a) */
var gHomeSys = "Galvo_sys_cc_neu_v31";
var gNumSys = 6;
var gFrameID = {
"frameset_main":"Galvo_sys_cc_neu_v31_slwebview_main_frameset",
"explorer":"Galvo_sys_cc_neu_v31_slwebview_explorer",
"frameset_model":"Galvo_sys_cc_neu_v31_slwebview_frame",
"model":"Galvo_sys_cc_neu_v31_slwebview_model",
"web":"Galvo_sys_cc_neu_v31_slwebview_web"};
var gIDMap = {
"Galvo_sys_cc_neu_v31":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"Galvo_sys_cc_neu_v31/PID":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"Galvo_sys_cc_neu_v31/PID/Clamping circuit":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"},
"CurrentComp_v20":{"target":"slwebview_4.svg","thumb":"slwebview_4_tb.png"},
"GalvoModel_v53":{"target":"slwebview_5.svg","thumb":"slwebview_5_tb.png"},
"CurrentComp_v20/Cc(s)":{"target":"slwebview_6.svg","thumb":"slwebview_6_tb.png"}};

