function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-Oct-2012 08:19:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0767045454545453 0.11 0.911813199848168 0.815]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create title
title('My title','FontSize',20,'FontName','High Tower Text','Color',[1 1 0]);

