function createfigure1
%CREATEFIGURE1

%  Auto-generated by MATLAB on 25-Feb-2016 07:51:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'DataAspectRatio',[1 1 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1.2 1.2]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.2 1.2]);
view(axes1,[-37.5 30]);
hold(axes1,'on');
axis off

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

% pie3 currently does not support code generation, enter 'doc pie3' for correct input syntax

% pie3(...);

