function createfigureAbtastung1(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE1(X1,Y1,X2,Y2,X3,Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  stem x
%  Y2:  stem y
%  X3:  stem x
%  Y3:  stem y

%  Auto-generated by MATLAB on 21-Nov-2013 20:11:24

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'ZMinorGrid','on','YMinorGrid','on',...
    'XTick',[-2 -1 0 1 2 3 4 5],...
    'XMinorGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.8 1]);
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create stem
stem(X2,Y2,'MarkerFaceColor',[0 0 1],'Marker','v','LineWidth',2,...
    'Color',[0 0 1]);

% Create stem
stem(X3,Y3,'MarkerFaceColor',[0 0 1],'Marker','^','LineWidth',2,...
    'Color',[0 0 1]);

% Create line
annotation(figure1,'line',[0.470754716981132 0.470754716981132],...
    [0.473729241877256 0.319494584837545],'LineWidth',2);

% Create line
annotation(figure1,'line',[0.502075471698113 0.502075471698113],...
    [0.473584837545127 0.319350180505415],'LineWidth',2);

% Create arrow
annotation(figure1,'arrow',[0.435849056603774 0.46811320754717],...
    [0.337545126353791 0.335595667870037],'HeadStyle','plain','LineWidth',2);

% Create arrow
annotation(figure1,'arrow',[0.539622641509434 0.503773584905661],...
    [0.337545126353791 0.335740072202167],'HeadStyle','plain','LineWidth',2);

