function legendPlace(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 14-May-2014 16:23:45

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.297343383584588 0.827624999999987 0.0858458961474037 0.115665584415584]);

