%function [speedSamples] = speedtestAuswertung(varargin) 
% SPEEDTESTAUSWERTUNG( LOGFILE ) 
% LOGFILE:  path to a speedtest logfile, default:
% '/media/storage/kabelBW_longtimeSpeedtest/analysed'
%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   KabelBW speed test automation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% if ~nargin 
    logfile = '/media/storage/kabelBW_longtimeSpeedtest/analysed';
% else
%    if ischar(varargin{1})
%       logfile=varargin{1};
%    end
% end

preprocessScript = '~/scripts/speedtestAutomation -preproc';

system(preprocessScript)

global in t1 
fd=fopen(logfile); 
in=textscan(fd,'%f %s %s %s'); 
fclose(fd); 
%
for k=1:length(in{3})
    in{3}{k}=[in{3}{k} ' ' in{4}{k}];
end
%%
tmp1=cellfun(@strsplit, in{3}, 'UniformOutput', false);

% datum von uhrzeit isolieren
for k=1:length(tmp1)
   time.date(k) = tmp1{k}(1);
   time.clock(k) = tmp1{k}(2);
end
%%
in{3}=[time.date]';
time.dateNum = datenum(time.date);

% xnum = time.dateNum;
%% X Axes - ranges and ticks
startDate = time.dateNum(1);
endDate = time.dateNum(end);
maxTickLabels = 12;                       % maximum count of x-axis tick labels 
ndays = diff([datenum(startDate), datenum(endDate)]);       % how many days 
tickDelta = ceil(ndays/maxTickLabels);
xnum = linspace(startDate, endDate,...
                  length(time.dateNum));           % x comp. vector of datenums
xData = [startDate:tickDelta:endDate]';   % x ticks vector

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Plot analysis
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
f1=figure(1); clf; 
SUB=220;

% time domain datarates
su(1)=subplot(2,2,[1 2]);
   %br=stairs(xnum, in{1});
br=stem(xnum, in{1},'-');
set(br,'Marker','none');
title('KabelBW Langzeit-Speedtest');

%% Formatting axes  of time domain plot 
ylabel(su(1), in{2}{1});
su(1).XTick = xData;                         % set x-tick datenums
set(  su(1),'XTick', xData, 'XLim', [startDate endDate],...
      'XMinorGrid', 'on', 'XMinorTick', 'on' );
datetick(su(1),'x','dd/mmm','keepticks');    % translate to date strings

%% Ausreißer entfernen
idx = find(in{1} < 15);
if length(idx) <= 320      % Wenn 100 oder weniger ausreißer forhanden...
	in{1}(idx) = [];        % ... samples entfernen und weiter machen!
   in{2}(idx,:)=[];
   in{3}(idx,:)=[];
   in{4}(idx,:)=[];
else
   fprintf('Zu viele Ausreißer: %i Stück', length(idx))
end
su(2) = subplot(SUB+3);
su(3) = subplot(SUB+4);

nbins = [65 55*3];
hist(su(2), in{1}, nbins(1));
hist(su(3), in{1}, nbins(2));
xlabel(su(2), in{2}(1)');
xlabel(su(3), in{2}(1)');

yr = get(su(2),'YLim');
round((yr(2)-yr(1))/2);

for k=2:3
   subplot(su(k));
   me=mean(in{1}); 
   line([me me], [0 max(ylim)],'Color','red','LineStyle','--');
   text(me, max(ylim)*.83,'mean',...
                     'FontName','Liberation Mono',...
                     'BackgroundColor',[0 1 0],...
                     'HorizontalAlignment','Center');
end

%  Auto-generated by MATLAB on 18-Jul-2015 18:12:53

% Create textbox
annotation(gcf,'textbox',...
   [0.156524278676988 0.174468077079197 0.11752287584898 0.212765965473995],...
   'String',{'KabelBW','contract:   100Mbit','Logs count: 1251',...
             'First log:  22-May','Last log:   16-Jul','Meas. periode:  1h'},...
   'LineStyle','none',...
   'FontName','Liberation Mono',...
   'BackgroundColor',[0 1 0]);

% strInfo = sprintf('Kabel-BW contract:   100Mbit\nLogs count:   %i\nStart date:   %s\nEnd date:   %s',...
%     length(in{1}), datestr(startDate), datestr(endDate)); 
% t1=text(su(2),11,yr(1)+round((yr(2)-yr(1))*2/3), strInfo,...
%    'BackgroundColor','green');%,'Interpreter','none');
% set(t1,'FontSize',10);
title(su(2),['Speedtest | ' num2str(nbins(1)) '-bins Histogramm']);
title(su(3),['Speedtest | ' num2str(nbins(2)) '-bins Histogramm']);
% xlim([10, 25]);


return;

%%
idx.aday = (datenum(in{4}) < datenum('20:00:00')) & (datenum(in{4}) > datenum('07:00:00'))
in{4}(idx.aday)
%& 

%%
% end
%%

% mainster@X58A-UD7:~$ cat scripts/speedtestAutomationAuswertung 
% #!/bin/bash
% #
% LOGPATH="/media/storage/kabelBW_longtimeSpeedtest"
% LOGNAME="kabelSpeedAnalysis"
% SPEEDS="/media/storage/kabelBW_longtimeSpeedtest/speeds"
% DATES="/media/storage/kabelBW_longtimeSpeedtest/dates"
% 
% SAVED="$LOGPATH/$LOGNAME"
% 
% 
% cat $SAVED | grep -e "Download:" | awk '{print $2 "," $3}' > $SPEEDS
% cat $SAVED | grep -e "Speedtest #" | awk '{print $2 "," $3}' > $DATES
% 
% pr -mts, $SPEEDS $DATES | sed '/^,/d; s/,/ /g' > "$LOGPATH/analysed"
% 
% echo 'read the script, matlab visualization is already implemented'
% # MATLAB script
% #####################
% # clear inT* xnum in 
% #
% # fd=fopen('/media/storage/kabelBW_longtimeSpeedtest/analysed'); 
% # in=textscan(fd,'%f %s %s %s'); 
% # fclose(fd); 
% #
% # for k=1:length(in{3})
% #     in{3}{k}=[in{3}{k} ' ' in{4}{k}];
% # end
% #
% # xnum=datenum(in{3});
% #
% # f1=figure(1); clf; 
% # su(1)=subplot(211);
% # br=stairs(xnum, in{1})
% # set(su(1),'XTick', linspace(startDate,endDate,20))
% # ylabel(su(1), in{2}{1})
% #
% # datetick(su(1),'x','dd/mmm')
% #
% # su(2)=subplot(212);
% # hist(in{1},100)
% # xlabel(su(2), in{2}{1})


