/* Generated by Report Generator v3.14 (R2013a) */
var gHomeSys = "GalvoModel_v3_discret_simo";
var gNumSys = 3;
var gFrameID = {
"frameset_main":"GalvoModel_v3_discret_simo_slwebview_main_frameset",
"explorer":"GalvoModel_v3_discret_simo_slwebview_explorer",
"frameset_model":"GalvoModel_v3_discret_simo_slwebview_frame",
"model":"GalvoModel_v3_discret_simo_slwebview_model",
"web":"GalvoModel_v3_discret_simo_slwebview_web"};
var gIDMap = {
"GalvoModel_v3_discret_simo":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"GalvoModel_v3_discret_simo/PID":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"GalvoModel_v3_discret_simo/current ctrl":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"}};

