/* Generated by Report Generator v3.14 (R2013a) */
var gHomeSys = "GalvoModel_v53";
var gNumSys = 1;
var gFrameID = {
"frameset_main":"GalvoModel_v53_slwebview_main_frameset",
"explorer":"GalvoModel_v53_slwebview_explorer",
"frameset_model":"GalvoModel_v53_slwebview_frame",
"model":"GalvoModel_v53_slwebview_model",
"web":"GalvoModel_v53_slwebview_web"};
var gIDMap = {
"GalvoModel_v53":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"}};

